"""init

Revision ID: e91fed8b299e
Revises: 4fb7e6af49e1
Create Date: 2025-07-01 16:27:40.063901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91fed8b299e'
down_revision: Union[str, Sequence[str], None] = '4fb7e6af49e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
