
name: Python application

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
      - name: Install the project dependencies
        working-directory: flask-api
        run:
            poetry install --with dev
      - name: Run black
        working-directory: flask-api
        run: poetry run black .
      - name : Set PYTHONPATH GLOBAL
        run : |
            cd flask-api
            echo PYTHONPATH=$(pwd):$PYTHONPATH >> $GITHUB_ENV
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          path: "./flask-api/backend/test/funcionality/users/test_user.py"
          max-line-length: "88"

      - name: Test
        run: |
           cd flask-api
           pwd
        
           poetry run pytest
        env:
            SUPABASE_DATABASE_URL: "sqlite:///:memory:"


            
